# Generated by Django 5.0.6 on 2024-06-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stage',
            field=models.IntegerField(),
        ),
    ]
